#!/bin/bash

if [ $# -eq 0 ]
then
    echo "Usage:phone searchfor[...searchfor]"
    echo "(You didn't tell me what you want to search for.)"
else
    for arg in "$@";do
	args="${args}|${arg}"	
	done
     egrep -i "${args:1}" data | awk -f display.awk
fi
